### ISSUE TITLE
Visual suggestion

### ISSUE THREAD

**Issue by cykq** [Juloos/MCDatapack.BacapTracker#1]
It would be nice if you could choose presets for the scoreboard. For example, I don't want my pages to be constantly flipping, it attracts too much attention. I would like to see him like this:
![image](https://github.com/Juloos/MCDatapack.BacapTracker/assets/121945639/db5e967b-8747-4245-aeb0-b3461388eda4)

Well, or smaller in size, where there are 5 categories (I'm just too lazy to photoshop), and scroll through them using /trigger bac_tracker:display/page_1/2/3

**Comment by Juloos** [comment]
The python script that generates the different pages depending on the number of milestones can be actually well customized, I can make it take as arguments the number of pages (up to 5 max) and the number of milestones per page easily.
Apart from that, it is impossible to move the location of the progress bar itself.

**Comment by Juloos** [comment]
Now configurable using 'config.json'
