### ISSUE TITLE
Advancements leaderboard

### ISSUE THREAD

**Issue by cykq** [Juloos/MCDatapack.BacapTracker#2]
I always wanted to find a person who can implement command that will display the leaderboard achievements, or is this possible only on plugins? /trigger bac_tracker:leaderboard for example

**Comment by Juloos** [comment]
What do you mean by leaderboard achievements? Maybe a small drawing would be better understanding

**Comment by cykq** [comment]
Like here, but instead of coins - achievements
![image](https://github.com/Juloos/MCDatapack.BacapTracker/assets/121945639/fd664db7-046c-4cf7-aac1-b6be9fe13147)

![image](https://github.com/Juloos/MCDatapack.BacapTracker/assets/121945639/31268069-7026-4a19-8919-5491d49dd3dd)

**Comment by Juloos** [comment]
Done
